### PR TITLE
added mp3 output option

### PR DESCRIPTION
**Pull request by psyntium**

### CODE REVIEW

**Comment by chughts** [comment]
@psyntium you need to accept the CLA, and default setting should remain as something that is Watson STT friendly.

**Comment by psyntium** [comment]
Hi,

I just did it. Thanks for the quick link!

**Comment by chughts** [comment]
I am happy to accept this pull request, but please reset the default line 78 ffmpeg-conversion.html to  

`format: {value: 'wav'},`

**Comment by psyntium** [comment]
done!

**Pull request merged**
